<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('missions')->insert([
            [
                'name' => '出身地は？地元のオススメのお土産は？',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 1,
                'program_id' => 1,
                'team_id' => 1,
                'mission_base_id' => 1,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d'),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '出身地は？地元のオススメのお土産は？',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 2,
                'program_id' => 1,
                'team_id' => 1,
                'mission_base_id' => 1,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d'),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '出身地は？地元のオススメのお土産は？',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 3,
                'program_id' => 1,
                'team_id' => 1,
                'mission_base_id' => 1,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d'),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '中学と高校の部活動それぞれ何部だった？',
                'detail' => 'test',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 1,
                'program_id' => 1,
                'team_id' => 1,
                'mission_base_id' => 2,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d'),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '中学と高校の部活動それぞれ何部だった？',
                'detail' => 'test',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 2,
                'program_id' => 1,
                'team_id' => 1,
                'mission_base_id' => 2,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+2 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '中学と高校の部活動それぞれ何部だった？',
                'detail' => 'test',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 3,
                'program_id' => 1,
                'team_id' => 1,
                'mission_base_id' => 2,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+2 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '田中さんの第一印象を一言で（20字以内）',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 1,
                'program_id' => 1,
                'team_id' => 1,
                'mission_base_id' => 3,
                'target_user_id' => 3,
                'delivery_order_date' => date('Y/m/d', strtotime('+3 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '田中さんの第一印象を一言で（20字以内）',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 2,
                'program_id' => 1,
                'team_id' => 1,
                'mission_base_id' => 3,
                'target_user_id' => 2,
                'delivery_order_date' => date('Y/m/d', strtotime('+3 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '田中さんの第一印象を一言で（20字以内）',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 3,
                'program_id' => 1,
                'team_id' => 1,
                'mission_base_id' => 3,
                'target_user_id' => 1,
                'delivery_order_date' => date('Y/m/d', strtotime('+3 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '好きな画像をアップしてみよう',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 1,
                'program_id' => 2,
                'team_id' => 2,
                'mission_base_id' => 4,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+1 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '好きな画像をアップしてみよう',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 4,
                'program_id' => 2,
                'team_id' => 2,
                'mission_base_id' => 4,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d'),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '自分の苦手なことを一つあげるとすると何だろう？（20字以内）',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 1,
                'program_id' => 2,
                'team_id' => 2,
                'mission_base_id' => 5,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+2 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '自分の苦手なことを一つあげるとすると何だろう？（20字以内）',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 4,
                'program_id' => 2,
                'team_id' => 2,
                'mission_base_id' => 5,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+2 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '今月のチームの目標は何ですか？（20字以内）',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 1,
                'program_id' => 2,
                'team_id' => 2,
                'mission_base_id' => 6,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+3 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '今月のチームの目標は何ですか？（20字以内）',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 4,
                'program_id' => 2,
                'team_id' => 2,
                'mission_base_id' => 6,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+3 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '今、仕事で一番大変なことは何ですか？（20字以内）',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 5,
                'program_id' => 3,
                'team_id' => 3,
                'mission_base_id' => 7,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+1 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '今、仕事で一番大変なことは何ですか？（20字以内）',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 6,
                'program_id' => 3,
                'team_id' => 3,
                'mission_base_id' => 7,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d'),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => 'このチームの満足度は10段階中どれくらいですか？',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 5,
                'program_id' => 3,
                'team_id' => 3,
                'mission_base_id' => 8,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d'),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => false
            ],
            [
                'name' => 'このチームの満足度は10段階中どれくらいですか？',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 6,
                'program_id' => 3,
                'team_id' => 3,
                'mission_base_id' => 8,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d'),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => false
            ],
            [
                'name' => '過去に学級委員をやったことはありますか？',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 5,
                'program_id' => 3,
                'team_id' => 3,
                'mission_base_id' => 9,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+2 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '過去に学級委員をやったことはありますか？',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 6,
                'program_id' => 3,
                'team_id' => 3,
                'mission_base_id' => 9,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+2 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => true
            ],
            [
                'name' => '今のチームについて考えてみよう',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 5,
                'program_id' => 3,
                'team_id' => 3,
                'mission_base_id' => 10,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+3 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => false
            ],
            [
                'name' => '今のチームについて考えてみよう',
                'detail' => 'Detail mission',
                'thumbnail_url' => 'brand/1632966849.png',
                'user_id' => 6,
                'program_id' => 3,
                'team_id' => 3,
                'mission_base_id' => 10,
                'target_user_id' => null,
                'delivery_order_date' => date('Y/m/d', strtotime('+3 day', strtotime(date('Y-m-d')))),
                'created_at' => date('Y/m/d H:i:s'),
                'time_required' => '30分',
                'is_anonymous' => false
            ],
        ]);
    }
}
